#if !defined(AFX_DQCHART_H__79695F6F_9E47_4271_95A8_D07628A06A9B__INCLUDED_)
#define AFX_DQCHART_H__79695F6F_9E47_4271_95A8_D07628A06A9B__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CDQChart wrapper class

class CDQChart : public CWnd
{
protected:
	DECLARE_DYNCREATE(CDQChart)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xaeaa9c65, 0x8c52, 0x11d3, { 0xab, 0xff, 0x0, 0x40, 0x5, 0x5d, 0xe8, 0x9 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	long GetYmin();
	void SetYmin(long);
	long GetYmax();
	void SetYmax(long);
	short GetChannel();
	void SetChannel(short);
	short GetStep();
	void SetStep(short);
	BOOL GetLock();
	void SetLock(BOOL);
	long GetXmax();
	void SetXmax(long);
	BOOL GetMarkWdqEvent();
	void SetMarkWdqEvent(BOOL);
	long GetDigitalMask();
	void SetDigitalMask(long);

// Operations
public:
	void Chart(const VARIANT& Data);
	void ChartEx(short* Buffer, short Channel, short Total);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_DQCHART_H__79695F6F_9E47_4271_95A8_D07628A06A9B__INCLUDED_)
